pipeline:
  build:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    registry: dev.enecuum.com:2087
    repo: dev.enecuum.com:2087/site/frontend
    tags: latest
    debug: true
    when:
      branch:
        - dev
      event:
        - push
        - tag
  build-beta:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    registry: dev.enecuum.com:2087
    repo: dev.enecuum.com:2087/site/frontend
    tags: beta
    when:
      branch:
        - beta
      event:
        - push
        - tag
  notify-build-telegram:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    when:
      branch:
        - dev
        - beta
      status:
        - success
        - failure
      event:
        - push
        - tag
  notify-build-zulip:
    image: dev.enecuum.com:2087/library/drone-zulip:v1.0.0
    secrets: [zulip_domain, zulip_bot_email, zulip_bot_api_key, zulip_stream]
    when:
      branch:
        - dev
        - beta
      status:
        - success
        - failure
      event:
        - push
        - tag
  deploy-beta:
    image: peloton/drone-rancher
    url: https://dev.enecuum.com:2096
    secrets:
      - source: rancher_access_key
        target: PLUGIN_ACCESS_KEY
      - source: rancher_secret_key
        target: PLUGIN_SECRET_KEY
    docker_image: dev.enecuum.com:2087/site/frontend:beta
    service: site/frontend-beta
    confirm: true
    timeout: 240
    when:
      branch:
        - beta
      status:
        - success
      event:
        - push
        - tag
  deploy-dev:
    image: peloton/drone-rancher
    url: https://dev.enecuum.com:2096
    secrets:
      - source: rancher_access_key
        target: PLUGIN_ACCESS_KEY
      - source: rancher_secret_key
        target: PLUGIN_SECRET_KEY
    docker_image: dev.enecuum.com:2087/site/frontend:latest
    service: site/frontend-dev
    confirm: true
    timeout: 240
    when:
      branch:
        - dev
      status:
        - success
      event:
        - push
        - tag
  deploy-prod:
    image: peloton/drone-rancher
    url: https://dev.enecuum.com:2096
    secrets:
      - source: rancher_access_key
        target: PLUGIN_ACCESS_KEY
      - source: rancher_secret_key
        target: PLUGIN_SECRET_KEY
    docker_image: dev.enecuum.com:2087/site/frontend:latest
    service: site/frontend-prod
    confirm: true
    timeout: 240
    when:
      branch:
        - master
      status:
        - success
      event:
        - push
        - tag
  notify-deploy-dev-telegram:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    message: \u2705 ${DRONE_REPO}:`${DRONE_COMMIT_BRANCH}` ${DRONE_BUILD_NUMBER} staging deployment successful
    when:
      branch:
        - dev
        - beta
      status:
        - success
      event:
        - push
        - tag
  notify-deploy-dev-zulip:
    image: dev.enecuum.com:2087/library/drone-zulip:v1.0.0
    secrets: [zulip_domain, zulip_bot_email, zulip_bot_api_key, zulip_stream]
    message: \u2705 ${DRONE_REPO}:`${DRONE_COMMIT_BRANCH}` ${DRONE_BUILD_NUMBER} staging deployment successful
    when:
      branch:
        - dev
        - beta
      status:
        - success
      event:
        - push
        - tag
  notify-deploy-prod-telegram:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    message: \u2705 ${DRONE_REPO}:`${DRONE_COMMIT_BRANCH}` ${DRONE_BUILD_NUMBER} production deployment successful
    when:
      branch:
        - master
      status:
        - success
      event:
        - push
        - tag
  notify-deploy-prod-zulip:
    image: dev.enecuum.com:2087/library/drone-zulip:v1.0.0
    secrets: [zulip_domain, zulip_bot_email, zulip_bot_api_key, zulip_stream]
    message: \u2705 ${DRONE_REPO}:`${DRONE_COMMIT_BRANCH}` ${DRONE_BUILD_NUMBER} production deployment successful
    when:
      branch:
        - master
      status:
        - success
      event:
        - push
        - tag
  notify-pr:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    message: \u2757 PR ${DRONE_REPO_LINK}/pull/${DRONE_PULL_REQUEST}
    when:
      branch: master
      event: pull_request
